c-stdaux: workaround compiler error with clang 3.4 and __builtin_assume_aligned()
On centos:7.9.2009, we have clang-3.4.2-9.el7. While ancient, it works mostly
fine for including c-stdaux. Maybe not all features are actually working, but
at least we can include the header and use the features that work (and
which are relevant for NetworkManager to build on centos7).

Except for c_internal_assume_aligned()/__builtin_assume_aligned():

  $ echo '#include <c-stdaux-generic.h>' > a.c; clang -Isrc -Wall -std=c11 -c a.c

Gives:

  In file included from a.c:1:
  src/c-stdaux-generic.h:483:28: error: use of unknown builtin '__builtin_assume_aligned' [-Wimplicit-function-declaration]
          const uint8_t *m = c_assume_aligned((const uint8_t *)memory + offset, 2, 0);
                             ^
  src/c-stdaux-generic.h:306:53: note: expanded from macro 'c_assume_aligned'
  #define c_assume_aligned(_ptr, _alignment, _offset) c_internal_assume_aligned((_ptr), (_alignment), (_offset))
                                                      ^
  src/c-stdaux-generic.h:308:64: note: expanded from macro 'c_internal_assume_aligned'
  #  define c_internal_assume_aligned(_ptr, _alignment, _offset) __builtin_assume_aligned((_ptr), (_alignment), (_offset))
                                                                 ^
  ...

Note:

  $ echo | clang -dM -E -| grep clang
  #define __clang__ 1
  #define __clang_major__ 3
  #define __clang_minor__ 4
  #define __clang_patchlevel__ 2
  #define __clang_version__ "3.4.2 (tags/RELEASE_34/dot2-final)"